# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Tavily搜索配置文件
# 使用官方NeMo Agent Toolkit架构和现有的Tavily工具

general:
  use_uvloop: true

functions:
  tavily_search:
    _type: mcp_tool_wrapper
    url: "http://localhost:8080/sse"
    _type: tavily_internet_search
    transport: "sse"
    description: "Search the web using Tavily API for real-time information"
  # tetris_vision_analysis:
  #   _type: mcp_tool_wrapper
  #   llm_name: "multimodal_llm"
  #   url: "http://localhost:8080/sse"
  #   transport: "sse"
  #   # mcp_tool_name: image_description
  #   mcp_tool_name: get_current_time
  #   description: "Search the web using Tavily API for real-time information"


llms:
  # 使用用户提供的ModelScope API
  modelscope_llm:
    _type: openai
    model_name: "qwen3-235b-a22b-thinking-2507"
    api_key: "sk-567d445b24e54ca2a0805cd30877d74f"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    temperature: 0.7
    max_tokens: 2048

workflow:
  _type: react_agent
  tool_names:
    - tavily_search
    # - tetris_vision_analysis:
  llm_name: modelscope_llm
  verbose: true
  parse_agent_response_max_retries: 3
  max_iterations: 10

